name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-pip python3-dev \
              zip unzip openjdk-11-jdk curl libffi-dev libssl-dev \
              libsqlite3-dev zlib1g-dev libjpeg-dev

          python3 -m pip install --upgrade pip
          pip install buildozer Cython

      - name: Build APK
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: kalku1-apk
          path: bin/*.apk
